// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL0OwG9djDCzPQonlUyfLLhP5N6lSxyGo',
    appId: '1:472496571412:web:3506b4c601672fe9395301',
    messagingSenderId: '472496571412',
    projectId: 'fruit-hub-b190d',
    authDomain: 'fruit-hub-b190d.firebaseapp.com',
    storageBucket: 'fruit-hub-b190d.firebasestorage.app',
    measurementId: 'G-DEXHP8K2R5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHkWn3YjIBZbw7idUyPXszU42lmt1DjRo',
    appId: '1:472496571412:android:b320a745a15beab1395301',
    messagingSenderId: '472496571412',
    projectId: 'fruit-hub-b190d',
    storageBucket: 'fruit-hub-b190d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRIVV2a1s298Lk3oYPi_MXl_zGIy5KVsk',
    appId: '1:472496571412:ios:6e69f34bc52c0a6e395301',
    messagingSenderId: '472496571412',
    projectId: 'fruit-hub-b190d',
    storageBucket: 'fruit-hub-b190d.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRIVV2a1s298Lk3oYPi_MXl_zGIy5KVsk',
    appId: '1:472496571412:ios:6e69f34bc52c0a6e395301',
    messagingSenderId: '472496571412',
    projectId: 'fruit-hub-b190d',
    storageBucket: 'fruit-hub-b190d.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL0OwG9djDCzPQonlUyfLLhP5N6lSxyGo',
    appId: '1:472496571412:web:9a581b2de2718468395301',
    messagingSenderId: '472496571412',
    projectId: 'fruit-hub-b190d',
    authDomain: 'fruit-hub-b190d.firebaseapp.com',
    storageBucket: 'fruit-hub-b190d.firebasestorage.app',
    measurementId: 'G-8HEN8JT7DX',
  );
}
